aliases:
  - &restore-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v1-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &install yarn --no-progress --frozen-lockfile --ignore-engines

version: 2
jobs:
  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          command: yarn test
      - store_test_results:
          path: reports/junit

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-10